In [1]:
import pandas as pd
import numpy as np

## Variáveis categóricas

1. Alguns Links:
https://medium.com/@arthurlambletvaz/one-hot-encoding-o-que-%C3%A9-cd2e8d302ae0

####
https://towardsdatascience.com/all-about-categorical-variable-encoding-305f3361fd02

####
https://pbpython.com/categorical-encoding.html

####
https://www.geeksforgeeks.org/feature-encoding-techniques-machine-learning/

Até o momento discutimos muito sobre como tratar números nos nossos dados, porém quando estamos trabalhando com variáveis do tipo categórica, como devemos proceder? Podemos utilizar utilizar letras/palavras como entrada do modelo? Se não for possível usar letras/palavras como entrada de modelo, como devemos fazer?

Nesse notebook vamos discutir algumas maneira que podemos trabalhar com esse tipo dado

### Dados utilizados:
https://www.kaggle.com/lepchenkov/usedcarscatalog

1. É um conjunto de dados retirados de anúncios de carros de um jornal, e o principal objetivo é determinar o tempo que o carro ficará anunciado.

In [2]:
# Ler os dados
df = pd.read_csv('cars.csv')

#imprimir as primeiras colunas
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

In [3]:
## vamos imprimir os tipos de dados que estã contidos em cada coluna
df.dtypes

manufacturer_name     object
model_name            object
transmission          object
color                 object
odometer_value         int64
year_produced          int64
engine_fuel           object
engine_has_gas          bool
engine_type           object
engine_capacity      float64
body_type             object
has_warranty            bool
state                 object
drivetrain            object
price_usd            float64
is_exchangeable         bool
location_region       object
number_of_photos       int64
up_counter             int64
feature_0               bool
feature_1               bool
feature_2               bool
feature_3               bool
feature_4               bool
feature_5               bool
feature_6               bool
feature_7               bool
feature_8               bool
feature_9               bool
duration_listed        int64
dtype: object

In [4]:
## podemor ver que há muitas colunas que não são numéricas

## a primeiro alternativa é o chamado OneHotEncoder
## vamos usar a função do pandas 
### https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

#vamos fazer o teste com a coluna de cores?
df2 = pd.get_dummies(df, columns = ['color'])
df2.head()

,manufacturer_name,model_name,transmission,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,body_type,...,color_brown,color_green,color_grey,color_orange,color_other,color_red,color_silver,color_violet,color_white,color_yellow
0,Subaru,Outback,automatic,190000,2010,gasoline,False,gasoline,2.5,universal,...,0,0,0,0,0,0,1,0,0,0
1,Subaru,Outback,automatic,290000,2002,gasoline,False,gasoline,3.0,universal,...,0,0,0,0,0,0,0,0,0,0
2,Subaru,Forester,automatic,402000,2001,gasoline,False,gasoline,2.5,suv,...,0,0,0,0,0,1,0,0,0,0
3,Subaru,Impreza,mechanical,10000,1999,gasoline,False,gasoline,3.0,sedan,...,0,0,0,0,0,0,0,0,0,0
4,Subaru,Legacy,automatic,280000,2001,gasoline,False,gasoline,2.5,universal,...,0,0,0,0,0,0,0,0,0,0

In [5]:
## uma outra forma de resolver esse problema é criando uma nova coluna de frequẽncia de ocorrência de um termo:

## vamos calcular as frequências que cada termo aparece:
fq = df.groupby('model_name').size()/len(df)    

# aplicar no map na coluna desejada
df.loc[:, "{}_freq_encode".format('model_name')] = df['model_name'].map(fq)   

df.head(10)

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,model_name_freq_encode
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,False,True,False,True,True,True,16,0.001739
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,False,True,True,False,False,False,True,83,0.001739
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,False,False,True,True,151,0.002076
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,86,0.001090
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,True,True,False,False,False,False,True,7,0.001661
5,Subaru,Outback,automatic,silver,132449,2011,gasoline,False,gasoline,2.5,...,False,False,False,True,False,True,True,True,67,0.001739
6,Subaru,Forester,automatic,black,318280,1998,gasoline,False,gasoline,2.5,...,False,False,True,True,False,False,True,True,307,0.002076
7,Subaru,Legacy,automatic,silver,350000,2004,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,73,0.001661
8,Subaru,Outback,automatic,grey,179000,2010,gasoline,False,gasoline,2.5,...,True,True,True,True,True,True,True,True,87,0.001739
9,Subaru,Forester,automatic,silver,571317,1999,gasoline,False,gasoline,2.5,...,True,False,False,True,False,False,False,True,43,0.002076

In [6]:
## Além disso podemos criar features binárias
## vamos trabalhar com a coluna engine_fuel

df['engine_fuel_binario'] = np.where(df['engine_fuel'] == 'gasoline', 1, 0)
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,model_name_freq_encode,engine_fuel_binario
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,False,True,False,True,True,True,16,0.001739,1
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,True,True,False,False,False,True,83,0.001739,1
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,False,True,True,151,0.002076,1
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,86,0.001090,1
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,True,False,False,False,False,True,7,0.001661,1

## Agora é como vocês, façam a transformação das variáveis categóricas de todo DataSet

1. Você deve aplicar todas as opções vistas até o momento
2. A escolha de qual método aplicar em uma determinada coluna é sua
3. Lembrar de excluir as colunas transformadas